# Here we are applying PCA which is a dimensionality reduction technique after doing this we will use RANDOM FOREST algorithm to train our model. 
# Accuracy is checked for PCA components as 10, 5 and 2.
# We got same accuracy with all three cases we solved 

In [47]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline

In [48]:
# here we are going to use brest cancer datset present in sklearn

from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [49]:
cancer= load_breast_cancer()

In [50]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [53]:
x = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
x.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [59]:
y = pd.DataFrame(cancer['target'])

In [60]:
print(y)

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]


In [62]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [63]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

In [65]:
from sklearn.decomposition import PCA
PCA=PCA()
x_train=PCA.fit_transform(x_train)
x_test=PCA.transform(x_test)

In [66]:
exp_var=PCA.explained_variance_ratio_
print(exp_var)

[4.46660523e-01 1.88395278e-01 9.43933146e-02 6.60752849e-02
 5.32524566e-02 3.96056026e-02 2.26087365e-02 1.61315960e-02
 1.34976791e-02 1.17358893e-02 9.54476572e-03 8.72180894e-03
 7.99243757e-03 5.02135350e-03 3.18302765e-03 2.64883811e-03
 2.02127407e-03 1.82345645e-03 1.45119557e-03 1.01550797e-03
 9.75723623e-04 8.50548844e-04 7.02975999e-04 6.25304667e-04
 4.91714481e-04 2.62350649e-04 2.24421915e-04 5.42683589e-05
 2.78432896e-05 4.82188492e-06]


## CASE1--
## Applying PCA to reduce our 30 dimentional data into 10 dimension and then applying RANDOM FOREST algorithm.

In [67]:
from sklearn.decomposition import PCA
PCA=PCA(n_components=10)
x_train=PCA.fit_transform(x_train)
x_test=PCA.transform(x_test)

In [69]:
from sklearn.ensemble import RandomForestClassifier
cls=RandomForestClassifier(max_depth=2,random_state=0)
cls.fit(x_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [71]:
y_pred=cls.predict(x_test)

In [72]:
from sklearn.metrics import accuracy_score
print('accuracy',accuracy_score(y_test,y_pred))

accuracy 0.9210526315789473


In [73]:
from sklearn.metrics import confusion_matrix 
  
cm = confusion_matrix(y_test, y_pred)

In [74]:
print(cm)

[[38  3]
 [ 6 67]]


# CASE2--
## PCA using 5 components only for 30 dimensional dataset


In [75]:
from sklearn.decomposition import PCA
PCA=PCA(n_components=5)
x_train=PCA.fit_transform(x_train)
x_test=PCA.transform(x_test)

In [87]:
exp_var=PCA.explained_variance_ratio_
print(exp_var)

[0.52624022 0.2219609 ]


In [76]:
from sklearn.ensemble import RandomForestClassifier
cls=RandomForestClassifier(max_depth=2,random_state=0)
cls.fit(x_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [77]:
y_pred=cls.predict(x_test)

In [78]:
from sklearn.metrics import accuracy_score
print('accuracy',accuracy_score(y_test,y_pred))

accuracy 0.9210526315789473


In [79]:
from sklearn.metrics import confusion_matrix 
  
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[37  4]
 [ 5 68]]


## CASE3--
## PCA with 2 components 

In [81]:
from sklearn.decomposition import PCA
PCA=PCA(n_components=2)
x_train=PCA.fit_transform(x_train)
x_test=PCA.transform(x_test)

In [86]:
exp_var=PCA.explained_variance_ratio_
print(exp_var)

[0.52624022 0.2219609 ]


In [82]:
from sklearn.ensemble import RandomForestClassifier
cls=RandomForestClassifier(max_depth=2,random_state=0)
cls.fit(x_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [83]:
y_pred=cls.predict(x_test)

In [84]:
from sklearn.metrics import accuracy_score
print('accuracy',accuracy_score(y_test,y_pred))

accuracy 0.9210526315789473


In [85]:
from sklearn.metrics import confusion_matrix 
  
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[37  4]
 [ 5 68]]
